#
# Dotfiles
# Alacritty
#

[window]
option_as_alt = "Both"

# Environment Variables
[env]
# Set the TERM environment variable
TERM = "xterm-256color"

# Font Configuration
[font]
# Font size in points
size = 12.0

[font.normal]
# Font family (default depends on OS)
family = "JetBrains Mono"
style  = "Regular"

# Color Scheme: Gruvbox Dark
[colors.primary]
# Background and foreground
background = "#282828"  # dark background
foreground = "#ebdbb2"  # light foreground

[colors.normal]
# Standard 8-color ANSI palette
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
# Bright variants of ANSI colors
black   = "#928374"
red     = "#fb4934"

